### ISSUE TITLE
Express zip download issue

### ISSUE THREAD

**Issue by thomath555** [orangewise/s3-zip#55]
I am trying to create a zip and send it using expressJS. The following is the code I am using

```
app.get('/', (req, res) => {
  res.setHeader("content-type", 'application/octet-stream');
  res.setHeader('Content-Disposition', 'attachment; filename=file.zip');
  s3Zip
    .archive({ region: 'us-east-1', bucket: 'botuploads.collectcdn.com', debug: true }, '5c5bbe28ac8153155159c3e4/44F01219-C9FE-4619-AAE6-37105E2E2CBE/', ['0_Resume (8).pdf'])
    .pipe(res);
});
```

I am getting a file called file.zip when i invoke the url via browser. But when i try to open it it shows the following error. What am i doing wrong? I want a direct link which can be used to download the zip file 
![Screenshot 2019-05-09 at 2 37 45 PM](https://user-images.githubusercontent.com/42599947/57441671-09515080-7268-11e9-8146-1568636186c8.png)

**Comment by thomath555** [comment]
I was able to make it work when I used the above code in my local server. But it breaks when used with lambda function

**Comment by CoconutTheSlayer** [comment]
Sooo, I made it finally working..

`npm intstall --save serverless-apigwy-binary`

`functions:
  handler:
    handler: handler.handler
    events:
      - http:
          method: get
          path: /
          contentHandling: CONVERT_TO_BINARY`

`module.exports.handler = serverless(app,{
  binary: ['application/zip'],
});`

**Comment by thomath555** [comment]
@CoconutTheSlayer Thanks for the help. Still the issue exists.
My serverless.yml is as follows

```
# serverless.yml

service: download-s3-to-zip
plugins:
  - serverless-apigwy-binary
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http:
          method: get
          path: /
          contentHandling: CONVERT_TO_BINARY
```

and my index.js is as follows

const serverless = require('serverless-http');
const express = require('express');
const s3Zip = require('s3-zip');
const app = express();

```
app.get('/', (req, res) => {
  res.setHeader("accept", 'application/zip');
  res.setHeader("Content-Type", 'application/json');
  res.setHeader('Content-Disposition', 'attachment; filename=file.zip');
  const zipFile = s3Zip.archive({ region: 'us-east-1', bucket: 'botuploads.collectcdn.com', debug: true }, 'blah/', hi.pdf', 'hello.jpg']);
  zipFile.pipe(res)
});

module.exports.handler = serverless(app,{
  binary: ['application/zip'],
});
```
Isn't the code and configuration correct? Can it be because, I am having mac os and the node modules i deploy will be for mac os right? Will that be a reason

**Comment by thomath555** [comment]
> Sooo, I made it finally working.. this is how you can get it working with express and lambda
> 
> @tmo
> 
> ```
> npm intstall --save serverless-apigwy-binary
> ```
> 
> ```
> functions:
>   handler:
>     handler: handler.handler
>     events:
>       - http:
>           method: get
>           path: /
>           contentHandling: CONVERT_TO_BINARY
> ```
> 
> ```
> module.exports.handler = serverless(app,{
>   binary: ['application/zip'],
> });
> ```

**Comment by thomath555** [comment]
> Sooo, I made it finally working.. this is how you can get it working with express and lambda
> 
> @tmo
> 
> ```
> npm intstall --save serverless-apigwy-binary
> ```
> 
> ```
> functions:
>   handler:
>     handler: handler.handler
>     events:
>       - http:
>           method: get
>           path: /
>           contentHandling: CONVERT_TO_BINARY
> ```
> 
> ```
> module.exports.handler = serverless(app,{
>   binary: ['application/zip'],
> });
> ```

@CoconutTheSlayer Thanks for the help. Still the issue exists.
My serverless.yml is as follows

```
# serverless.yml

service: download-s3-to-zip
plugins:
  - serverless-apigwy-binary
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http:
          method: get
          path: /
          contentHandling: CONVERT_TO_BINARY
```

and my index.js is as follows

```
const serverless = require('serverless-http');
const express = require('express');
const s3Zip = require('s3-zip');
const app = express();
app.get('/', (req, res) => {
  res.setHeader("accept", 'application/zip');
  res.setHeader("Content-Type", 'application/json');
  res.setHeader('Content-Disposition', 'attachment; filename=file.zip');
  const zipFile = s3Zip.archive({ region: 'us-east-1', bucket: 'botuploads.collectcdn.com', debug: true }, 'blah/', hi.pdf', 'hello.jpg']);
  zipFile.pipe(res)
});

module.exports.handler = serverless(app,{
  binary: ['application/zip'],
});
```
Isn't the code and configuration correct? Can it be because, I am having mac os and the node modules i deploy will be for mac os right? Will that be a reason
